import { z } from "zod";
export declare const CreateOpportunityInputSchema: z.ZodObject<{
    name: z.ZodString;
    stage: z.ZodOptional<z.ZodString>;
    amount: z.ZodOptional<z.ZodNumber>;
    currency: z.ZodOptional<z.ZodString>;
    expectedCloseDate: z.ZodOptional<z.ZodString>;
    probability: z.ZodOptional<z.ZodNumber>;
    accountId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contactId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    leadId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    reasonLost: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    accountId?: string | null | undefined;
    contactId?: string | null | undefined;
    stage?: string | undefined;
    amount?: number | undefined;
    currency?: string | undefined;
    expectedCloseDate?: string | undefined;
    probability?: number | undefined;
    leadId?: string | null | undefined;
    reasonLost?: string | undefined;
}, {
    name: string;
    accountId?: string | null | undefined;
    contactId?: string | null | undefined;
    stage?: string | undefined;
    amount?: number | undefined;
    currency?: string | undefined;
    expectedCloseDate?: string | undefined;
    probability?: number | undefined;
    leadId?: string | null | undefined;
    reasonLost?: string | undefined;
}>;
export declare const UpdateOpportunityInputSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    stage: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    amount: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    currency: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    expectedCloseDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    probability: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    accountId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    contactId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    leadId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    reasonLost: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    accountId?: string | null | undefined;
    contactId?: string | null | undefined;
    stage?: string | undefined;
    amount?: number | undefined;
    currency?: string | undefined;
    expectedCloseDate?: string | undefined;
    probability?: number | undefined;
    leadId?: string | null | undefined;
    reasonLost?: string | undefined;
}, {
    name?: string | undefined;
    accountId?: string | null | undefined;
    contactId?: string | null | undefined;
    stage?: string | undefined;
    amount?: number | undefined;
    currency?: string | undefined;
    expectedCloseDate?: string | undefined;
    probability?: number | undefined;
    leadId?: string | null | undefined;
    reasonLost?: string | undefined;
}>;
export type CreateOpportunityInput = z.infer<typeof CreateOpportunityInputSchema>;
export type UpdateOpportunityInput = z.infer<typeof UpdateOpportunityInputSchema>;
